POST http://localhost:8080/api/avaliacoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDYyODUyLCJleHAiOjE2OTI1NDkyNTJ9.jCcp9g9KgRkkca1DKNmgMM4t5Uuj3uZgCabysBkZmLkgFwUkhKfyE-5RUEJdGcmW1TeazT-AAsrxpDmoVAZF5g


{
   "descricao": "Prova API Relacionamentos",
   "pessoa": {
      "id": 1
   }

}

###

GET http://localhost:8080/api/avaliacoes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDYyODUyLCJleHAiOjE2OTI1NDkyNTJ9.jCcp9g9KgRkkca1DKNmgMM4t5Uuj3uZgCabysBkZmLkgFwUkhKfyE-5RUEJdGcmW1TeazT-AAsrxpDmoVAZF5g
 
