POST http://localhost:8080/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDAzNDMzLCJleHAiOjE2OTI0ODk4MzN9.wwQZG8u8tGOYY9c-IG6SPjAkqQkdgNTiEN9W03oN42wApaDrv8mtR3TnC0NVDIAOMkXPgeu40496pbQ2o-MNIw
Authorization: 

{
   "descricao": "Tecnologia"
}

###

GET http://localhost:8080/api/categorias
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDAzNDMzLCJleHAiOjE2OTI0ODk4MzN9.wwQZG8u8tGOYY9c-IG6SPjAkqQkdgNTiEN9W03oN42wApaDrv8mtR3TnC0NVDIAOMkXPgeu40496pbQ2o-MNIw
 
