POST http://localhost:8080/api/eventos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDA0MTk1LCJleHAiOjE2OTI0OTA1OTV9.7XM5SqX91CgzY7LH0JRjs2K7GYts9tBsAOzQRzEojTEctSm1RHXsNxpr4eRc9e_UAgaKcMJdzARoDctWg7QKew

{
   "descricao": "Treinamento Banco de Dados PostgreSQL",
   "dataHora": "2023-08-18T19:49:00",
   "categoria": {
    "id": 2
   }
}

###

GET http://localhost:8080/api/eventos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDA0MTk1LCJleHAiOjE2OTI0OTA1OTV9.7XM5SqX91CgzY7LH0JRjs2K7GYts9tBsAOzQRzEojTEctSm1RHXsNxpr4eRc9e_UAgaKcMJdzARoDctWg7QKew