POST http://localhost:8080/api/pessoas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDY2MDEwLCJleHAiOjE2OTI1NTI0MTB9.bTvkBiyv0ohMOO6-VVD-pXL9LDFgzOgK_IMJh7rouScW5Nnv5_-p8OLxQNI2t2hyFsGM6CmEjcDGDXyp89ZJdg


{
   "nome": "Ciclano da Silva"

}

###

GET http://localhost:8080/api/pessoas
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDY2MDEwLCJleHAiOjE2OTI1NTI0MTB9.bTvkBiyv0ohMOO6-VVD-pXL9LDFgzOgK_IMJh7rouScW5Nnv5_-p8OLxQNI2t2hyFsGM6CmEjcDGDXyp89ZJdg
 
###

PUT http://localhost:8080/api/pessoas/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiaWF0IjoxNjkyNDY2MDEwLCJleHAiOjE2OTI1NTI0MTB9.bTvkBiyv0ohMOO6-VVD-pXL9LDFgzOgK_IMJh7rouScW5Nnv5_-p8OLxQNI2t2hyFsGM6CmEjcDGDXyp89ZJdg


{
   "nome": "Beltrano Rodrigues"
}